### ISSUE TITLE
How to share node-red code Please share like this)

### ISSUE THREAD

**Issue by crxporter** [crxporter/SonoffT1withBrian#1]
@bshurt - hello sir. Here are some pointers on copying Node-RED code. This will make it easy for us to see each other's code. 

You can make a new issue or go to an existing issue. You'll want to put the code in code fences. That looks like this:

```
This is text inside of a code fence.

To start you have a line that is just ``` - that's 3 of the character ` which is on the same key as a ~ ... so it's a lowercase ~
```

The best is to export from Node-RED to the clipboard. So select your nodes, then click "export". An example of how to do this with the MQTT code you need to check if your sonoff T1 is working properly is like this:

The flow looks like this:
<img width="440" alt="Screen Shot 2019-04-08 at 3 06 36 PM" src="https://user-images.githubusercontent.com/38265886/55753422-e9800000-5a0f-11e9-896b-9eb580d64fec.png">

The export looks like this:
<img width="517" alt="Screen Shot 2019-04-08 at 3 07 11 PM" src="https://user-images.githubusercontent.com/38265886/55753471-04eb0b00-5a10-11e9-8a1e-3e3dd8033d4c.png">
<img width="544" alt="Screen Shot 2019-04-08 at 3 07 37 PM" src="https://user-images.githubusercontent.com/38265886/55753494-146a5400-5a10-11e9-9e60-6a6c59e33008.png">

And the pasted Node-RED will look like this:
```
[{"id":"d351c6b8.1a493","type":"debug","z":"8508dd8e.e8afe8","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":380,"y":140,"wires":[]},{"id":"f7ec0b07.537ea8","type":"mqtt in","z":"8508dd8e.e8afe8","name":"","topic":"sonoff/t1","qos":"1","datatype":"auto","broker":"99cbe9a4.8001a","x":160,"y":140,"wires":[["d351c6b8.1a493"]]},{"id":"99cbe9a4.8001a","type":"mqtt-broker","z":"","name":"openhab mosquitto","broker":"192.168.0.124","port":"1883","clientid":"","usetls":false,"compatmode":true,"keepalive":"60","cleansession":true,"birthTopic":"","birthQos":"0","birthRetain":"false","birthPayload":"","closeTopic":"","closeQos":"0","closeRetain":"false","closePayload":"","willTopic":"","willQos":"0","willRetain":"false","willPayload":""}]
```

Make sure you have selected only the things you are trying to share! Otherwise it will send EVERYTHING in your node red.

This makes it super easy for us to share node-red code. We just triple-click that line with all the code, then hit "import" in node red and paste it. Much better than a hodge-podge of half-screen pictures.

**Comment by bshurt** [comment]
Ok.  Fair enough.

```test on typing into the code fence.

**Comment by bshurt** [comment]
```test````

**Comment by crxporter** [comment]
Still not right. The ``` need to be their own lines.

type "\`\`\`" - then a carriage return - then stuff - then a carriage return - then "\`\`\`"

I'm editing your comments above to be "right" - click "edit" on them to see what I did.
